name: my_local_auth
description: "Helper package to implement local auth"
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  local_auth: ^1.1.6
  stacked: ^2.2.1